### ISSUE TITLE
Why the specially privileged genesis validators?

### ISSUE THREAD

**Issue by jtremback** [gnuclear/atom-whitepaper#23]
This predetermined validator set sounds sketchy as hell. Who gets the validators, and why are they immune from being kicked out by someone who is staking more?

PoS already has distribution issues, but crowdsales are pretty well accepted at this point and you can just distribute coins with one of those. But I think that you will mostly face criticism about these genesis validators. Why not just let anyone stake who wants to, and kick off those people who don't have enough staked?

The fact that you need an arbitrary numerical limit on the number of validating boxes seems like a major weakness also. Might be interesting to look at some softer limit where those with less money staked get left out of the process sometimes?

**Comment by jaekwon** [comment]
We've gotten more feedback saying the opposite, that crowdsales are sketchy as hell, that people would like to see something more transparently distributed at least for genesis.  For example, of the top 50% funders for TheDAO, how many distinct individuals are actually represented there?  It could just be 1 person for all we know.  And what does that do for the security of the system?

Also, the token isn't meant to be a store-of-value or medium-of-transfer, for which crowdfunding is well suited for.  Wouldn't you rather have a transparently distributed genesis, one that can be shown to not be centralized in any locale, or centralized to any particular (rich) funder?  We think that the distribution scheme we proposed addresses those concerns, and shows an obvious answer to the PoS distribution problem -- distribute them manually, transparently.

But we're not only distributing gnuts to identified entities, we're also providing them to anyone who wants to burn/donate.  So it seems like a good balance.

Of course we'll face criticism.  Any scheme will face criticism.  But we won't get the same criticism that say, it was 100% premined or that the genesis distribution wasn't transparent.

The genesis validators are immune from being kicked out because there are enough validator spots that mathematically they can't get kicked out.  All 33 non-genesis-validator spots need to be filled before any of the 67 get kicked out.  If the 33 spots are filled with a non-equal distribution, then the smallest validators will be in the 33.  If the 33 spots are filled with equal distribution, then they still can't kick of the vesting validators out.  Also, over time there will be more spots available.

That there is a limit on the number of validators is a property of pubkey-based PoS.  There have been attempts to make do without such a limitation in first generation PoS cryptocurrencies, but they all suffer from issues.  Even Casper is looking at a cap on the number of validators now, as far as I know.  Also, Tendermint can handle more validators, but at the cost of bandwidth, meaning at the cost of commit speeds.  100 today is based on tradeoffs of decentralization vs that bandwidth requirement.  It's a provably necessary tradeoff that must be made, and we choose to make choices that favor high speed and sufficient global decentralization.

In all likelihood, the distribution of validator voting power will be rather unequal, and the smallest validator will probably have less than 0.1% of gnuts.  They can delegate to any of the other validators.  They won't be missing out!

**Comment by jtremback** [comment]
@jaekwon My understanding of our conversation last night:

1) There will be some split of initial gnuts between a foundation and a crowdsale.

2) There some fixed total number of validators at any time (IMO, it's unnecessary to complicate things by having it increase over time over something).

3) By staking more coins than the validator with the least coins staked, I can kick them out and take their spot.

4) If I don't have enough coins to do this, I can delegate validation to one of the existing validators. In doing this, my coins can be slashed if the validator cheats.

5) The validator in question can charge a percentage commission of the staking reward that my coins earn.

6) There will be a special first-day rate for the crowdsale. This is to reward people who are active enough in the community to know about it.

7) After this, the price will increase in a way similar to the Ethereum or DAO sales.

Is this all correct?

**Comment by jaekwon** [comment]
Yes.

The split will be 80/20.  In comparison, Ethereum had a 66.7/33.3 split without taking mining into account.

(3) will have to be defined better, to include delgation.  We might also need to include a `delta factor` or something to prevent flip-flopping of the small validators.

(5) there's the question of whether this commission is global or set individually.  I believe global will be sufficient, we can make it a non-parameter constant and punt on whether to allow this to be parameterized globally or locally.  I'll do a simulation with 10% and see what happens.

(6) isn't to reward active community members -- anyone who puts stake in is welcome. It's because the first day is so important.  It should be a token amount.
